version: "3.1"
services:
  db:
    image: postgres:9.5-alpine
    environment:
      - POSTGRES_DB=mainzelliste
      - POSTGRES_USER=mainzelliste
      - POSTGRES_PASSWORD=medickoeln2020
  mainzelliste:
    image: medicalinformatics/mainzelliste:1.8-latest
    ports:
      - 8080:8080
    environment:
      - ML_REVERSEPROXY_FQDN=mainzelliste
      - ML_REVERSEPROXY_SSL=false
      - ML_DB_PASS=medickoeln2020
      - POSTGRES_DB=mainzelliste
      - POSTGRES_USER=mainzelliste
      - POSTGRES_PASSWORD=medickoeln2020
      - ML_API_KEY=X3TVeiOPMjw3ZZrh5Y6ZAm76XhAv2wGg
      - ML_ALLOWEDREMOTEADDRESSES=0.0.0.0/0
    depends_on:
      - db
